services:
  minecraft:
    image: itzg/minecraft-server:java21-graalvm
    container_name: minecraft
    restart: always
    ports:
      - "25565:25565"
    environment:
      TZ: "Asia/Tokyo"
      EULA: "TRUE"
      VERSION: "1.21.1"
      TYPE: "PAPER"
      MEMORY: "2G"
      MOTD: "Welcome to my Minecraft server!"
      ENABLE_RCON: "true"
      # 今回使用したイメージでは、以下のような環境変数でサーバーに利用されるJVMのオプションを変更することもできます。
      # JVM_XX_OPTS: "-XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled"
    volumes:
      - ./data:/data
